import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { useState } from 'react';
import { Pagina, CabecalhoPagina } from '@core/components/ui/primitivos';
import { CALCULADORAS } from '@core/anima/calculosClinicos';
/** Bancada de Cálculo Clínico (bloco 5). Fins educacionais — não é conduta real. */
export function CalculadoraPage() {
    return (_jsxs(Pagina, { largura: 900, children: [_jsx(CabecalhoPagina, { titulo: "Bancada de C\u00E1lculo", subtitulo: "F\u00F3rmulas para praticar racioc\u00EDnio quantitativo \u2014 n\u00E3o substitui julgamento cl\u00EDnico real." }), _jsx("div", { style: { display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(320px, 1fr))', gap: 16 }, children: CALCULADORAS.map((c) => (_jsx(CartaoCalculadora, { calc: c }, c.id))) })] }));
}
function CartaoCalculadora({ calc }) {
    const [valores, setValores] = useState({});
    const [opcoes, setOpcoes] = useState(Object.fromEntries((calc.extras ?? []).map((e) => [e.chave, e.opcoes[0].v])));
    const numericos = Object.fromEntries(Object.entries(valores).map(([k, v]) => [k, parseFloat(v)]));
    const resultado = calc.calcular(numericos, opcoes);
    return (_jsxs("div", { style: { background: 'var(--color-bg-card)', border: '1px solid var(--color-border)', borderRadius: 'var(--radius-lg)', padding: 20 }, children: [_jsx("p", { style: { margin: '0 0 4px', fontSize: 14, fontWeight: 700, color: 'var(--color-text-primary)' }, children: calc.nome }), _jsx("p", { style: { margin: '0 0 16px', fontSize: 11, color: 'var(--color-text-muted)', fontFamily: 'var(--font-mono)' }, children: calc.formula }), _jsxs("div", { style: { display: 'flex', flexDirection: 'column', gap: 8, marginBottom: 12 }, children: [calc.campos.map((f) => (_jsxs("div", { style: { display: 'flex', alignItems: 'center', gap: 8 }, children: [_jsx("label", { style: { flex: 1, fontSize: 12, color: 'var(--color-text-secondary)' }, children: f.label }), _jsx("input", { type: "number", value: valores[f.chave] ?? '', onChange: (e) => setValores((v) => ({ ...v, [f.chave]: e.target.value })), style: { width: 90, padding: '6px 8px', background: 'var(--color-bg-base)', border: '1px solid var(--color-border)', borderRadius: 'var(--radius-sm)', color: 'var(--color-text-primary)', fontSize: 13 } }), _jsx("span", { style: { fontSize: 11, color: 'var(--color-text-muted)', width: 44 }, children: f.unidade })] }, f.chave))), calc.extras?.map((e) => (_jsxs("div", { style: { display: 'flex', alignItems: 'center', gap: 8 }, children: [_jsx("label", { style: { flex: 1, fontSize: 12, color: 'var(--color-text-secondary)' }, children: e.label }), _jsx("select", { value: opcoes[e.chave], onChange: (ev) => setOpcoes((o) => ({ ...o, [e.chave]: ev.target.value })), style: { padding: '6px 8px', background: 'var(--color-bg-base)', border: '1px solid var(--color-border)', borderRadius: 'var(--radius-sm)', color: 'var(--color-text-primary)', fontSize: 12 }, children: e.opcoes.map((op) => (_jsx("option", { value: op.v, children: op.label }, op.v))) })] }, e.chave)))] }), _jsx("div", { style: { borderTop: '1px solid var(--color-border)', paddingTop: 12 }, children: resultado ? (_jsxs(_Fragment, { children: [_jsxs("p", { style: { margin: 0, fontSize: 22, fontWeight: 700, color: 'var(--color-accent)', fontFamily: 'var(--font-mono)' }, children: [resultado.valor.toFixed(1), " ", _jsx("span", { style: { fontSize: 13, fontWeight: 400, color: 'var(--color-text-muted)' }, children: resultado.unidade })] }), resultado.interpretacao && _jsx("p", { style: { margin: '2px 0 0', fontSize: 12, color: 'var(--color-text-secondary)' }, children: resultado.interpretacao })] })) : (_jsx("p", { style: { margin: 0, fontSize: 12, color: 'var(--color-text-muted)' }, children: "Preencha os campos" })) })] }));
}
